name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      GREETING: "Hello from GitHub Actions!"
      AUTHOR: "Joshua"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run script with environment variables
        run: |
          echo "$GREETING"
          echo "Script executed by $AUTHOR"
